name: Bump Module Version

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      pull-requests: write
    steps:
      
      - uses: actions/checkout@v4
      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}